### PR TITLE
Remove kanban board workflows

### PR DESCRIPTION
**Pull request by lubosmj**
[noissue]

### CODE REVIEW

**Comment by mdellweg** [comment]
Don't they come from the plugin template?

**Comment by quba42** [comment]
@mdellweg I had the same thought [here](https://github.com/pulp/pulp_deb/pull/732#pullrequestreview-1330277123).

So what we really need is a parameter for `template_config.yml` to disable Kanban?

**Comment by mdellweg** [comment]
Oh, here there is no plugin template... XD

**Comment by lubosmj** [comment]
Yes. This file was added in https://github.com/pulp/pulp-cli-deb/commit/0bb8289d0ef4ebc618c6a6ff582abad91f030cd5. I think we can merge the PR.

\+ https://github.com/pulp/pulp_deb/pull/732#issuecomment-1460204267.

**Review by quba42 — APPROVED** [review]
The test failures are clearly unrelated (same failure in nightly).

**Pull request merged**
